UI-MVC/Models/ErrorViewModel.cs
namespace Basketbal.UI.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UI-MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Basketbal.UI.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Basketbal.UI.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

UI-MVC/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using Basketbal.BL;
using Basketbal.BL.Domain;
using Microsoft.AspNetCore.Mvc;

namespace Basketbal.UI.MVC.Controllers
{
    public class MatchController : Controller
    {
        private IManager _mgr;

        public MatchController(IManager mgr)
        {
            _mgr = mgr;
        }
        
        public IActionResult Index()
        {
            IEnumerable<Match> matches = _mgr.GetAllMatches();
            return View(matches);
        }

        public IActionResult Detail(int matchId)
        {
            Match match = _mgr.GetMatch(matchId);
            IEnumerable<Referee> referees = _mgr.GetAllRefereesAssignedToMatch(matchId);
            // kan ook 1 methode van _mgr oproepen die met include alles in 1x binnenhaalt, maar wou met viewbag experimenteren
            ViewBag.Referees = referees;
            return View(match);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Match match)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            _mgr.AddMatch(match.HomeTeam,match.AwayTeam, match.Date.ToString(), null);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult MatchFilterFranchiseAndDate()
        {
            return View();
        }

        public IActionResult MatchesOfFranchiseAndDate(string franchiseInput, string dateInput)
        {
            IEnumerable<Match> matches = _mgr.GetAllMatchesOfFranchiseAndDate(franchiseInput, dateInput);
            return View(matches);
        }
        
        public IActionResult SelectMatchToAddRefereeTo()
        {
            IEnumerable<Match> matches = _mgr.GetAllMatches();
            return View(matches);
        }

        public IActionResult AddRefereeToMatch(int MatchId, int RefereeId)
        {
            _mgr.AddRefereeToMatch(MatchId, RefereeId);
            return RedirectToAction("Detail", "Match", new {matchId = MatchId});
        }
        
        public IActionResult SelectMatchToRemoveRefereeFrom()
        {
            IEnumerable<Match> matches = _mgr.GetAllMatches();
            return View(matches);
        }

        public IActionResult RemoveRefereeFromMatch(int MatchId, int RefereeId)
        {
            _mgr.RemoveRefereeFromMatch(MatchId, RefereeId);
            return RedirectToAction("Detail", "Match", new {matchId = MatchId});
        }
    }
}

UI-MVC/Controllers/RefereeController.cs
using System.Collections.Generic;
using Basketbal.BL;
using Basketbal.BL.Domain;
using Microsoft.AspNetCore.Mvc;

namespace Basketbal.UI.MVC.Controllers
{
    public class RefereeController : Controller
    {
        private IManager _mgr;

        public RefereeController(IManager mgr)
        {
            _mgr = mgr;
        }
        
        public ActionResult Index()
        {
            return View();
        }
        
        public IActionResult Detail(int refereeId)
        {
            Referee referee = _mgr.GetReferee(refereeId);
            return View(referee);
        }

        public IActionResult SelectRefereeToAddToMatch(int MatchId)
        {
            IEnumerable<Referee> referees = _mgr.GetAllRefereesNotAssignedToMatch(MatchId);
            ViewBag.MatchId = MatchId;
            return View(referees);
        }
        
        public IActionResult SelectRefereeToRemoveFromMatch(int MatchId)
        {
            IEnumerable<Referee> referees = _mgr.GetAllRefereesAssignedToMatch(MatchId);
            ViewBag.MatchId = MatchId;
            return View(referees);
        }
    }
}

UI-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UI-MVC/Views/Match/Add.cshtml
@using Basketbal.BL.Domain
@model Basketbal.BL.Domain.Match

@{
    Layout = "_Layout";
    ViewBag.Title = "Add Match";
}

<h2>Add a Match</h2>

<form asp-controller="Match" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="HomeTeam"></label>
        <input asp-for="HomeTeam" class="form-control">
        <span asp-validation-for="HomeTeam" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="AwayTeam"></label>
        <input asp-for="AwayTeam" class="form-control">
        <span asp-validation-for="AwayTeam" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Date">Date</label>
        <input asp-for="Date" type="date" asp-format="dd/MM/yyyy" class="form-control">
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>
    <input type="submit" value="Submit">
</form>

UI-MVC/Views/Match/Detail.cshtml
@using Basketbal.BL.Domain
@model Basketbal.BL.Domain.Match

@{
    Layout = "_Layout";
    ViewBag.Title = "Match Details";
}

<h2>Match Details</h2><hr>
<table>
    <thead>
    <tr>
        <th class="table-header">MatchId</th>
        <th class="table-header">Home Team</th>
        <th class="table-header">Away Team</th>
        <th class="table-header">Date</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>@Model.MatchId</td>
        <td>@Model.HomeTeam</td>
        <td>@Model.AwayTeam</td>
        <td>@(Model.Date.Equals(null) ? "Not Mentioned" : Model.Date.ToString("dd MMMM yyyy"))</td>
    </tr>
    </tbody>
</table>

<br><br><br><br>
<h2>Referees</h2><hr>
<table>
    <thead>
    <tr>
        <th class="table-header">RefereeId</th>
        <th class="table-header">Name</th>
        <th class="table-header">UniformNumber</th>
        <th class="table-header">FoulDifferential</th>
        <th class="table-header">Type</th>
        <th class="table-header"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (Referee referee in @ViewBag.Referees)
    {
        <tr>
            <td>@referee.RefereeId</td>
            <td>@referee.Name</td>
            <td>@(referee.UniformNumber == null ? "Onbekend" : referee.UniformNumber+"")</td>
            <td>@referee.FoulDifferential</td>
            <td>@referee.Type.ToString()</td>
            <td><a asp-controller="Referee" asp-action="Detail" asp-route-refereeId="@referee.RefereeId">Details</a></td>
        </tr>
    }
    </tbody>
</table>

UI-MVC/Views/Match/Index.cshtml
@using Basketbal.BL.Domain
@model IEnumerable<Basketbal.BL.Domain.Match>

@{
    Layout = "_Layout";
    ViewBag.Title = "Matches";
}

<h2>All Matches</h2><hr>
<table>
    <thead>
    <tr>
        <th class="table-header">MatchId</th>
        <th class="table-header">Home Team</th>
        <th class="table-header">Away Team</th>
        <th class="table-header">Date</th>
        <th class="table-header"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (Match match in Model)
    {
        <tr>
            <td>@match.MatchId</td>
            <td>@match.HomeTeam</td>
            <td>@match.AwayTeam</td>
            <td>@(match.Date.Equals(null) ? "Not Mentioned" : match.Date.ToString("dd MMMM yyyy"))</td>
            <td><a asp-controller="Match" asp-action="Detail" asp-route-matchId="@match.MatchId">Details</a></td>
        </tr>
    }
    </tbody>
</table>

UI-MVC/Views/Match/MatchFilterFranchiseAndDate.cshtml
@model Basketbal.BL.Domain.Match
@{
    Layout = "_Layout";
    ViewBag.Title = "Filter Matches";
}

<h2>Enter the franchise and Date of which you'd like to see the matches.</h2><hr>
<form asp-controller="Match" asp-action="MatchesOfFranchiseAndDate" method="post">
    <div class="form-group">
        <label for="franchise">Franchise</label>
        <input type="text" id="franchise" name="franchiseInput" class="form-control">
    </div>
    <div class="form-group">
        <label for="date">Date</label>
        <input type="date" id="date" name="dateInput" class="form-control">
    </div>
    <input type="submit" value="Submit">
</form>

UI-MVC/Views/Match/MatchesOfFranchiseAndDate.cshtml
@using Basketbal.BL.Domain
@model IEnumerable<Basketbal.BL.Domain.Match>

@{
    Layout = "_Layout";
    ViewBag.Title = "Filtered Matches";
}

<h2>Match</h2><hr>
<table>
    <thead>
    <tr>
        <th class="table-header">MatchId</th>
        <th class="table-header">Home Team</th>
        <th class="table-header">Away Team</th>
        <th class="table-header">Date</th>
    </tr>
    </thead>
    <tbody>
    @foreach (Match match in @Model)
    {
        <tr>
            <td>@match.MatchId</td>
            <td>@match.HomeTeam</td>
            <td>@match.AwayTeam</td>
            <td>@(match.Date.Equals(null) ? "Not Mentioned" : match.Date.ToString("dd MMMM yyyy"))</td>
        </tr>
    }
    </tbody>
</table>

UI-MVC/Views/Match/SelectMatchToAddRefereeTo.cshtml
@using Basketbal.BL.Domain
@model IEnumerable<Basketbal.BL.Domain.Match>

@{
    Layout = "_Layout";
    ViewBag.Title = "Add Referee to Match";
}

<h2>Select the match you'd like to add a referee to</h2><hr>
<table>
    <thead>
    <tr>
        <th class="table-header">MatchId</th>
        <th class="table-header">Home Team</th>
        <th class="table-header">Away Team</th>
        <th class="table-header">Date</th>
        <th class="table-header"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (Match match in @Model)
    {
        <tr>
            <td>@match.MatchId</td>
            <td>@match.HomeTeam</td>
            <td>@match.AwayTeam</td>
            <td>@(match.Date.Equals(null) ? "Not Mentioned" : match.Date.ToString("dd MMMM yyyy"))</td>
            <td><a asp-controller="Referee" asp-action="SelectRefereeToAddToMatch" asp-route-MatchId="@match.MatchId">Select</a></td>
        </tr>   
    }
    </tbody>
</table>

UI-MVC/Views/Match/SelectMatchToRemoveRefereeFrom.cshtml
@using Basketbal.BL.Domain
@model IEnumerable<Basketbal.BL.Domain.Match>
@{
    Layout = "_Layout";
    ViewBag.Title = "Remove Referee from Match";
}

<h2>Select the match you'd like to remove a referee from</h2><hr>
<table>
    <thead>
    <tr>
        <th class="table-header">MatchId</th>
        <th class="table-header">Home Team</th>
        <th class="table-header">Away Team</th>
        <th class="table-header">Date</th>
        <th class="table-header"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (Match match in @Model)
    {
        <tr>
            <td>@match.MatchId</td>
            <td>@match.HomeTeam</td>
            <td>@match.AwayTeam</td>
            <td>@(match.Date.Equals(null) ? "Not Mentioned" : match.Date.ToString("dd MMMM yyyy"))</td>
            <td><a asp-controller="Referee" asp-action="SelectRefereeToRemoveFromMatch" asp-route-MatchId="@match.MatchId">Select</a></td>
        </tr>   
    }
    </tbody>
</table>

UI-MVC/Views/Referee/Detail.cshtml
@model Basketbal.BL.Domain.Referee
@{
    ViewBag.Title = "Referee Details";
    Layout = "_Layout";
}

<h2>Referee Details</h2><hr>
<table>
    <thead>
    <tr>
        <th class="table-header">RefereeId</th>
        <th class="table-header">Name</th>
        <th class="table-header">UniformNumber</th>
        <th class="table-header">FoulDifferential</th>
        <th class="table-header">Type</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>@Model.RefereeId</td>
        <td>@Model.Name</td>
        <td>@(Model.UniformNumber == null ? "Onbekend" : Model.UniformNumber+"")</td>
        <td>@Model.FoulDifferential</td>
        <td>@Model.Type.ToString()</td>
    </tr>
    </tbody>
</table>

UI-MVC/Views/Referee/Index.cshtml
@{
    Layout = "_Layout";
}

UI-MVC/Views/Referee/SelectRefereeToAddToMatch.cshtml
@using Basketbal.BL.Domain
@model IEnumerable<Basketbal.BL.Domain.Referee>

@{
    Layout = "_Layout";
    ViewBag.Title = "Add Referee";
}
<h2>Select the referee you'd like to add to this match</h2><hr>
<table>
    <thead>
    <tr>
        <th class="table-header">RefereeId</th>
        <th class="table-header">Name</th>
        <th class="table-header">UniformNumber</th>
        <th class="table-header">FoulDifferential</th>
        <th class="table-header">Type</th>
        <th class="table-header"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (Referee referee in @Model)
    {
        <tr>
            <td>@referee.RefereeId</td>
            <td>@referee.Name</td>
            <td>@(referee.UniformNumber == null ? "Onbekend" : referee.UniformNumber+"")</td>
            <td>@referee.FoulDifferential</td>
            <td>@referee.Type.ToString()</td>
            <td><a asp-controller="Match" asp-action="AddRefereeToMatch" asp-route-MatchId="@ViewBag.MatchId" asp-route-RefereeId="@referee.RefereeId">Add</a></td>
        </tr>   
    }
    </tbody>
</table>

UI-MVC/Views/Referee/SelectRefereeToRemoveFromMatch.cshtml
@using Basketbal.BL.Domain
@model IEnumerable<Basketbal.BL.Domain.Referee>

@{
    Layout = "_Layout";
    ViewBag.Title = "Remove Referee";
}
<h2>Select the referee you'd like to remove from this match</h2><hr>
<table>
    <thead>
    <tr>
        <th class="table-header">RefereeId</th>
        <th class="table-header">Name</th>
        <th class="table-header">UniformNumber</th>
        <th class="table-header">FoulDifferential</th>
        <th class="table-header">Type</th>
        <th class="table-header"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (Referee referee in @Model)
    {
        <tr>
            <td>@referee.RefereeId</td>
            <td>@referee.Name</td>
            <td>@(referee.UniformNumber == null ? "Onbekend" : referee.UniformNumber+"")</td>
            <td>@referee.FoulDifferential</td>
            <td>@referee.Type.ToString()</td>
            <td><a asp-controller="Match" asp-action="RemoveRefereeFromMatch" asp-route-MatchId="@ViewBag.MatchId" asp-route-RefereeId="@referee.RefereeId">Remove</a></td>
        </tr>   
    }
    </tbody>
</table>

UI-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - NBA Match Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Match" asp-action="Index">NBA Match Management</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Match" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Match" asp-action="Add">Add Match</a></li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Match" asp-action="MatchFilterFranchiseAndDate">Filter Matches</a></li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Match" asp-action="SelectMatchToAddRefereeTo">Add Referee To Match</a></li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Match" asp-action="SelectMatchToRemoveRefereeFrom">Remove Referee From Match</a></li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Now.Year - KdG - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>